site_name: geOrchestra main documentation

repo_url: https://github.com/georchestra/georchestra
repo_name: georchestra

docs_dir: docs
edit_uri: edit/main/docs/


theme:
  language: en
  features:
    # - toc.integrate
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
  logo: images/georchestra-logo-white.svg
  favicon: images/favicon.ico
  name: material

extra:
  # version:
  #  provider: mike
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:psc@georchestra.org
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/georchestra
    - icon: fontawesome/brands/github
      link: https://github.com/georchestra
    - icon: fontawesome/brands/google
      link: https://groups.google.com/g/georchestra?hl=en
    - icon: fontawesome/brands/dev
      link: https://groups.google.com/group/georchestra-dev?hl=fr
    - icon: fontawesome/regular/comments
      link: https://matrix.to/#/#georchestra:osgeo.org


copyright: '© 2025 - geOrchestra'

extra_css:
    - css/extra.css

extra_javascript:
    - assets/custom_versions.js

# arborescence de 1er et 2e niveau à gérer ici
# Ces entrées correspondent au modèle de documentation
# Here do not put .fr or .en in the name of the markdown : the i18n plugin manage this for you

nav:
    - Home: index.md 
#    - User guide:
#        - Summary: user_guide/index.md
    - Administration guide:
#        - Summary: admin_guide/index.md

        - Global rights management:
          - admin_guide/rights_management/index.md
          - admin_guide/rights_management/acl-sp.md
          - admin_guide/rights_management/acl-gateway.md
        - Users management:
          - admin_guide/users_management/index.md
          - admin_guide/users_management/users.md
          - admin_guide/users_management/organizations.md
          - admin_guide/users_management/roles.md
        - Users rights management:
          - admin_guide/users_rights_management/index.md
          - admin_guide/users_rights_management/acl-geonetwork.md
          - admin_guide/users_rights_management/acl-geoserver.md
          - admin_guide/users_rights_management/acl-geofence.md
          - admin_guide/users_rights_management/acl-mapstore.md
          - admin_guide/users_rights_management/acl-cadastrapp.md
        - Datahub:
          - admin_guide/datahub/index.md
        - Styling: admin_guide/styling.md
        - Architecture: admin_guide/architecture/index.md
        - Post-deploy config: admin_guide/post-deploy_config.md
        - Geonetwork:
          - Synchronization: admin_guide/geonetwork_synchronization.md
          - Custom Form: admin_guide/gn_custom_form/gn_custom_form.md
    - Installation guide:
        - Summary: install_guide/index.md
        - Prerequisites: install_guide/prerequisites.md
        - Configuration: install_guide/configuration.md
        - Setup DB: install_guide/postgresql.md
        - SASL configuration: install_guide/sasl.md
        - Apps:
          - Geoserver:
            - Clustering: install_guide/apps/geoserver_clustering.md
            - Datadir: install_guide/apps/geoserver_data_dir_versioning.md
          - OpenLDAP: install_guide/apps/openldap.md
          - Geonetwork:
            - Setup: install_guide/apps/geonetwork4.md
            - Upgrade: install_guide/apps/upgrade_geonetwork.md
          - Cas: install_guide/apps/cas6.md
          - Datafeeder: install_guide/apps/datafeeder.md
#        - Versions: install_guide/versions.md
        - Servers:
            - Apache: install_guide/servers/apache.md
            - Tomcat:
              - Setup: install_guide/servers/tomcat.md
              - Deploy wars: install_guide/servers/tomcat_deploy_wars.md
    - Developer guide:
        - Version number: developer_guide/version_number.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - callouts
  # - toc-md:
      # toc_page_title: Contents
      # toc_page_description: Summary of the section
      # header_level: 3
      # pickup_description_meta: false
      # pickup_description_class: false
      # output_path: tableofcontent.md
      # output_log: true
      # ignore_page_pattern: index.md
      # remove_navigation_page_pattern: index.md
      # template_dir_path: custom_template
  - i18n:
        docs_structure: suffix
        fallback_to_default: true
        reconfigure_material: true
        reconfigure_search: true
        languages:
          - locale: en
            name: English
            default: true
            build: true
            site_name: "geOrchestra main documentation"

  - git-revision-date-localized:
      enable_creation_date: true
  
  - exclude:
      glob:
        - tableofcontent.md
